// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skfhfmgkedadauznlzan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrZmhmbWdrZWRhZGF1em5semFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDc3MTMsImV4cCI6MjA3MzUyMzcxM30.TWYpwJWRcCnXRdSH1hKie8o0RYdw4SZ_Q2570fMQnoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});